name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      - name: Unity - Request Activation File
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-request-activation-file@2338dd09663a155e2fc6a45511330c90f11af1ca
        uses: game-ci/unity-request-activation-file@v2.0.0
        with:
          # Version of unity to use for building the project.
          unityVersion: 2021.3.14f1

      - name: Unity - Builder
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-builder@9f79830454d37cd9e70c4c3b73d26c06bcce2b2a
        uses: game-ci/unity-builder@v2.1.2
        with:
          # Platform that the build should target.
          targetPlatform: webgl
          # Version of unity to use for building the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt
          # Specific docker image that should be used for building the project
          buildName: build
          projectPath: ./STDgame
          

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
